### PR TITLE
Finalsprint amy

### PR DESCRIPTION
**Pull request by morettiamye**
Not sure what the conflict is thats preventing merge.  Just adding data to tables.

### CODE REVIEW

**Review by criveracrum — CHANGES_REQUESTED** [review]
Fails to build 
Problems:
Line 22 of Price.java 
private int "workspace_size"; //change to variable name

Other issues:
Caused by: org.postgresql.util.PSQLException: ERROR: INSERT has more expressions than target columns
  Position: 77
Failed to execute SQL script statement #3 of URL

**Comment by morettiamye** [comment]
`BUILD SUCCESSFUL in 27s`

**Comment by azadoza** [comment]
There was a merge issue, some data.sql tables were repeated from old versions. Schema.sql also was not in table order and would pop up issues that tables still existed when you rerun. I fixed these sql files but this still doesnt build

**Comment by morettiamye** [comment]
It is actually fixed this time, pinky promise.

```amy@MacBook-Pro demo % ./gradlew build

> Task :test
2021-11-16 10:37:16.629  INFO 74344 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-11-16 10:37:16.633  INFO 74344 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-11-16 10:37:16.637  INFO 74344 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

BUILD SUCCESSFUL in 26s
7 actionable tasks: 5 executed, 2 up-to-date```

**Comment by morettiamye** [comment]
``` amy@MacBook-Pro demo % ./gradlew bootRun

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.4)

2021-11-16 10:38:18.351  INFO 74585 --- [  restartedMain] e.d.s.g.takeaseat.demo.DemoApplication   : Starting DemoApplication using Java 11.0.11 on MacBook-Pro.local with PID 74585 (/Users/amy/Documents/code/depaul/Take-A-Seat/demo/build/classes/java/main started by amy in /Users/amy/Documents/code/depaul/Take-A-Seat/demo)
2021-11-16 10:38:18.356  INFO 74585 --- [  restartedMain] e.d.s.g.takeaseat.demo.DemoApplication   : The following profiles are active: dev
2021-11-16 10:38:18.433  INFO 74585 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-11-16 10:38:18.434  INFO 74585 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-11-16 10:38:20.461  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-11-16 10:38:20.462  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-11-16 10:38:20.531  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.featured.FeaturedRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
2021-11-16 10:38:20.535  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.price.PriceNoSQLRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
2021-11-16 10:38:20.541  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.reservation.NewsfeedRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
2021-11-16 10:38:20.548  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.review.ReviewRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
2021-11-16 10:38:20.557  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.team.TeamReviewRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
2021-11-16 10:38:20.605  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 133 ms. Found 9 JPA repository interfaces.
2021-11-16 10:38:20.623  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-11-16 10:38:20.624  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2021-11-16 10:38:20.629  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.employee.EmployeeRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.637  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.amenities.AmenitiesRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.639  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.building.BuildingRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.641  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.employee.EmployeeRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.647  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.price.PriceRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.652  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.reservation.ReservationRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.655  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.spaces.SpacesRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.658  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.team.TeamRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.662  INFO 74585 --- [  restartedMain] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface edu.depaul.se452.group4.takeaseat.demo.workspace.WorkspaceRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
2021-11-16 10:38:20.684  INFO 74585 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 58 ms. Found 5 MongoDB repository interfaces.
2021-11-16 10:38:22.414  INFO 74585 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-11-16 10:38:22.424  INFO 74585 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-11-16 10:38:22.424  INFO 74585 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.52]
2021-11-16 10:38:22.517  INFO 74585 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-11-16 10:38:22.517  INFO 74585 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4082 ms
2021-11-16 10:38:23.471  INFO 74585 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-11-16 10:38:23.816  INFO 74585 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-11-16 10:38:25.104  INFO 74585 --- [  restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-11-16 10:38:25.149  INFO 74585 --- [  restartedMain] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.32.Final
2021-11-16 10:38:25.254  INFO 74585 --- [  restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2021-11-16 10:38:25.334  INFO 74585 --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
2021-11-16 10:38:28.122  INFO 74585 --- [  restartedMain] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-11-16 10:38:28.130  INFO 74585 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-11-16 10:38:30.396  INFO 74585 --- [  restartedMain] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2021-11-16 10:38:30.447  INFO 74585 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketReadException: Prematurely reached end of stream
        at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:112) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:647) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:512) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:355) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:279) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:107) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:62) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:144) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188) ~[mongodb-driver-core-4.2.3.jar:na]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) ~[mongodb-driver-core-4.2.3.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:836) ~[na:na]

2021-11-16 10:38:30.718  INFO 74585 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2021-11-16 10:38:31.708  WARN 74585 --- [  restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-11-16 10:38:32.250  INFO 74585 --- [  restartedMain] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2021-11-16 10:38:33.505  INFO 74585 --- [  restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2021-11-16 10:38:33.571  INFO 74585 --- [  restartedMain] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@e06dae75, org.springframework.security.web.context.SecurityContextPersistenceFilter@a2214f3a, org.springframework.security.web.header.HeaderWriterFilter@553cab8f, org.springframework.web.filter.CorsFilter@c585ece6, org.springframework.security.web.csrf.CsrfFilter@effca1c9, org.springframework.security.web.authentication.logout.LogoutFilter@c8890b2b, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@76585586, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@681645f7, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@4dcb5fd6, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@e00b17a3, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@7a062e24, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@1ed06522, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5d5c9910, org.springframework.security.web.session.SessionManagementFilter@7eebe012, org.springframework.security.web.access.ExceptionTranslationFilter@c9d80106, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@f757f4ef]
2021-11-16 10:38:34.256  INFO 74585 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-11-16 10:38:34.304  INFO 74585 --- [  restartedMain] e.d.s.g.takeaseat.demo.DemoApplication   : Started DemoApplication in 16.535 seconds (JVM running for 17.311)
begin encoded
Take-A-Seat Dev/Main 
end encoded
<==========---> 80% EXECUTING [1m 31s]
> :bootRun
```

**Review by criveracrum — APPROVED** [review]
Everything works for me (tested reservations, dashboard, spaces, etc.)

**Review by azadoza — APPROVED** [review]
builds

**Pull request merged**
